### ISSUE TITLE
RM521F

### ISSUE THREAD

**Issue by agent462** [iamromulan/RM520N-GL#1]
Hey - Curious whether you have the RM521F firmware that could be put here or in a new repo.  I need to do a fresh firmware flash.

**Comment by iamromulan** [comment]
Sorry i didn't see this until now. 
I plan to eventually create a 521 firmware, most of my free time has been pretty busy though so what time i do have i am focused on the toolkit project. 
https://mega.nz/file/7Q1DjSLJ#C7EicrIRcGRG2bsz92Q27VA_zfTE6IAfFTgiUsbanYk

'''
AT+QCFG="ResetFactory" seems to be stronger than a firmware flash. Even restores the IMEI to a previous value in most cases.
